#!/bin/bash

SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
TARGET="/Volumes/ORMEROD/"
if [ ! -d "$TARGET" ]; then
  echo "SD card not found"
  exit 1
fi

rsync -av --modify-window=1 --delete --exclude '.*' "$SOURCE" "$TARGET"
